logging.level.root: info
logging.file.name: ./log/application.log

setting:
  build:
    date: 2023-06-07
  version:
    jdk: JetBrains Runtime 17
    jcef: 111
    openlayers: 7.3.0
    angular: 16.0.4
    opencv: 4.7.0
  git:
    address: https://gitee.com/CrimsonHu/java_map_download
  web:
    prod: true

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db.sqlite3

mybatis:
  mapper-locations: classpath*:com/jmd/db/dao/mapper/*Mapper.xml

okhttp:
  connect-timeout: 7500
  read-timeout: 7500
  write-timeout: 7500
  max-idle-connections: 1024
  keep-alive-duration: 5000

tile:
  block-divide: 289

download:
  retry: 1

pool:
  thread:
    tile-calculation: 12
    tile-download: 256  